spring.datasource.url=jdbc:mysql://localhost:3306/java_backend_test
spring.datasource.username=root
spring.datasource.password=${DB_TEST_PASSWORD}
#spring.datasource.password=afshin9584V

#spring.jwt.secretKey=${JWT_SECRET}


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.user=root
spring.flyway.password=${DB_PASSWORD}
spring.flyway.enabled=true