CREATE TABLE users (
    id BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    password VARCHAR(255) NULL,
    `role` VARCHAR(255) NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE demos (
    id BIGINT AUTO_INCREMENT NOT NULL,
    title VARCHAR(255) NULL,
    location VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    user_id BIGINT NULL,
    CONSTRAINT pk_demos PRIMARY KEY (id)
);

ALTER TABLE demos
    ADD CONSTRAINT FK_DEMOS_ON_USER
    FOREIGN KEY (user_id)
    REFERENCES users (id);